### ISSUE TITLE
option to output html and css that create exact replica what it look in terminal  

### ISSUE THREAD

**Issue by mobop** [charmbracelet/glow#141]
convert terminal output to html and css

**Comment by KharmaScribbles** [comment]
Ooo, this is a nice idea. I have been learning HTML/CSS so this sounds like an interesting project.. however I'd need to find a good way to parse the theme into css, since not everyone will be using the defaults.

Not saying I am going to take this on, I am new to coding and git.. but I liked this idea, HTML/CSS is the only 'language' I use (and it's not even really a language I guess..)

---
### Hey! I tipped you for the nice idea!
<details>
<summary>Details</summary>

![bravetip2](https://user-images.githubusercontent.com/36386908/76152283-fde2d780-607a-11ea-9039-6ebf44377458.png)

`https://publishers.basicattentiontoken.org/` | - - Verify your Github there to claim your tips!
> You don't need to use Brave browser to receive tips, but I recommend it - it supports Chrome features and extensions too!
 
</details>
<sup> Actually, all Github users should read the details and verify themselves so they can receive tips too!</sup>

**Comment by muesli** [comment]
Nice idea, indeed. We can already output the HTML, we'd just need to write a CSS stylesheet for it.

**Comment by mobop** [comment]
@muesli status?

**Comment by muesli** [comment]
Planned, but no progress as of yet.

**Comment by mobop** [comment]
i am out

**Comment by muesli** [comment]
@mobop Please don't just close this ticket, as we're still planning to work on it. If you want to stop being notified about it, you can click the "Unsubscribe" button on the right.

**Comment by mobop** [comment]
your design is broken

**Comment by muesli** [comment]
@mobop If you have encountered a specific issue with the design, please file a separate ticket.

**Comment by samueldaniel** [comment]
you can get pretty close with [terminal-to-html](https://github.com/buildkite/terminal-to-html)

`glow README.md --style dark | terminal-to-html -preview > out.html`
