### ISSUE TITLE
Pager live preview

### ISSUE THREAD

**Issue by morpheusthewhite** [charmbracelet/glow#148]
A good additional feature would be a pager mode with a live preview, allowing to modify the file and preview its changes in real time (even better would be to have some sort of analogue of the `synctex`, but probably that's out of the scope of this tool)

**Comment by mschloesser** [comment]
I would love to see this feature too! I tried to fiddle with `watch` and some quick and dirty helper scripts but an actual "live preview" would be great.

**Comment by muesli** [comment]
Agreed, that would be nice.

**Comment by BachoSeven** [comment]
This would close #135 as well.

**Comment by Lisiadito** [comment]
I would love to see that feature as well. 
@mschloesser can you share your script until the feature is implemented? Because I didn't get it to work with watch.

**Comment by shitchell** [comment]
I feel like this shouldn't be too hard.

https://medium.com/@skdomino/watch-this-file-watching-in-go-5b5a247cf71f

Using fsnotify, you could create a file watcher to detect any edits to the current document. Any time there's an edit, re-read the file and update `m.currentDocument.Body`. No promises that I won't get distracted or otherwise not get around to it, but I'll *probably* look at this over the weekend.

**Comment by shitchell** [comment]
So we've got 3 parts to this:

1. Initialize a watcher (should only happen once after you launch glow)
2. Add a new filepath to the watcher (should happen each time you view a local file)
3. Remove a filepath from the watcher (should happen each time you stop viewing a local file / return to file list)

@meowgorithm  @muesli

Do you guys have any suggestions where each step should live? I'm *thinking* first add the watcher as an attribute of pagerModel.  `setContent()` gets run every time we both open a new file *and* when we re-render the document (e.g. after detecting a file change). I don't think there presently exists a single method that runs only when we first open a file, so perhaps add another attribute to pager like `isViewingFile bool`, and then adding a block to `setContent()` such as:

```go
if !isViewingFile:
  isViewingFile = true
  if isLocalFile:
    addWatcher(currentFilePath)
```

and then toggle `isViewingFile` to false and remove the watcher whenever you call `unload()`. Does that seem reasonable? Or would there be a better way to implement this? Since I'm still not super familiar with the code, I wanted to ask before implementing it :P

**Comment by mschloesser** [comment]
> I would love to see that feature as well.
> @mschloesser can you share your script until the feature is implemented? Because I didn't get it to work with watch.

@Lisiadito Unfortunately, I deleted the scripts since it didn't really work well. 

Another thing that, imho, would be important is to maintain the scrolling position. When you're editing a really long document you don't want to scroll back to the position of the last change every time.

**Comment by shitchell** [comment]
> Another thing that, imho, would be important is to maintain the scrolling position. When you're editing a really long document you don't want to scroll back to the position of the last change every time.

Totally agreed. in `pager.go`, you can update the current document by editing the contents of `m.currentDocument.Body`. Then you run `renderWithGlamour(m, m.currentDocument.Body)` to re-render/update the view. And it keeps the current position :) As an example, you could drop this into `pager.go` beneath `switch msg.String()` and above `case "q", "esc":`

```go
case "1":
	m.currentDocument.Body = m.currentDocument.Body + "\n\nhere's a new line."
	cmd = renderWithGlamour(m, m.currentDocument.Body)
	cmds = append(cmds, cmd)
```

Then launch glow, open a file, and type "1" repeatedly. It'll keep appending lines to the end of the document, but as the file changes, the scroll position remains the same.

**Comment by morpheusthewhite** [comment]
Temporary (or maybe not) solution for those needed this to integrate it with a terminal editor such as vim: there is this nice plugin https://github.com/npxbr/glow.nvim

**Comment by muesli** [comment]
Closing a few tickets describing the same feature. Let's track this in #135, which was the first ticket suggesting it.
