### ISSUE TITLE
Using L key, instead of enter, to open a file

### ISSUE THREAD

**Issue by matildeopbravo** [charmbracelet/glow#254]
Since I'm using vim keys to browse my local files, I find it inconvenient to have to reach enter key to open a file. Since using H key to go back is already supported, I'd suggest using L to open a file, that way  it's intuitive since they are "opposite".

**Comment by meowgorithm** [comment]
That's actually very smart, however we're currently using <kbd>h</kbd> and <kbd>l</kbd> for prev/next page in the context of the file browser. I'm a little cautious of remapping those keys as we may need them 

<kbd>space</kbd> is available (though funny enough it's often used to jump to the next page).

**Comment by matildeopbravo** [comment]
Oh my bad! Since I don't usually have a lot of files, I didn't actually notice that it was already in use. Since space is available, I'd suggest mapping that to opening the file, I find it more convenient than enter.

Thank you!

**Comment by cyhyraethz** [comment]
Adding `space` to open a file would be a nice addition since it's easier to reach than `enter`.

Could even possibly use `Shift+H` and `Shift+L` (or `Shift+J` and `Shift+K`) to browse left/right in the file browser, which would free up `l` to use for opening files. Most people probably use `/` to find their file when there's multiple pages anyway, though having a convenient way to browse is obviously important too.
