### ISSUE TITLE
Backslash doesn't escape

### ISSUE THREAD

**Issue by Disonantemus** [charmbracelet/glow#488]
With _this_ markdown file:
~~~
# H1 Title
\# Hash Symbol 
~~~
I get _something_ like:
~~~
[ H1: Title ]
\# Hash Symbol
~~~
Expected:
~~~
[ H1: Title ]
# Hash Symbol
~~~
Github Flavour:
# H1: Title
\# Hash Symbol
---
**Tested expected behavior with:**  
https://daringfireball.net/projects/markdown/dingus
https://spec.commonmark.org/dingus/
https://jbt.github.io/markdown-editor/
https://dillinger.io/

**Comment by bashbunni** [comment]
Thank you for bringing this to our attention along with some examples of how it should look. I just checked the issues in [Glamour](https://github.com/charmbracelet/glamour), our markdown renderer used in Glow, and this issue is already documented over there. I will close this for being a duplicate, but this is a great reminder for us that Glamour needs a bit of love! 
https://github.com/charmbracelet/glamour/issues/106
